# -*- coding: utf-8 -*-
"""Clipping_program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2Iymv7WXp4gkh-AKFZ3aeRzm7oDn1Mq
"""

!pip install pandas openpyxl ffmpeg-python

import pandas as pd
import subprocess
import os

# Input files
excel_file = "timestamps.xlsx"


# Output directory
output_dir = "clips"
os.makedirs(output_dir, exist_ok=True)

# Read Excel file
df = pd.read_excel(excel_file)

for index, row in df.iterrows():

    video_file = str(row["video_file"])
    clip_name = str(row["Output"])
    start_time = str(row["start_time"])
    end_time = str(row["end_time"])

    output_file = os.path.join(output_dir, f"{clip_name}.mp4")

    command = [
        "ffmpeg",
        "-i", video_file,
        "-ss", start_time,
        "-to", end_time,
        "-c", "copy",
        output_file,
        "-y"
    ]

    subprocess.run(command)

    print(f"Created: {output_file}")

print("Finished!")